sonar.projectKey=First1CSonar
sonar.projectName=First1CSonar
sonar.projectVersion=1.0

sonar.sources=src

sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000

sonar.token=sqp_762da4bdab468ff2cc35168633e7ebb5b6a0cb5f


