sonar.projectKey=First1CSonar
sonar.projectName=First1CSonar
sonar.projectVersion=1.0

# Исходный код
sonar.sources=./src

# Адрес SonarQube
sonar.host.url=http://localhost:9000

# Токен
sonar.token=sqp_762da4bdab468ff2cc35168633e7ebb5b6a0cb5f

# Кодировка
sonar.sourceEncoding=UTF-8

# Какие файлы анализировать
sonar.inclusions=**/*.bsl,**/*.os

# Не учитывать .gitignore
sonar.scm.exclusions.disabled=true

sonar.inclusions=**/*.bsl,**/*.os

sonar.scm.exclusions.disabled=true

