sonar.web.javaOpts=-Xmx1024m -Xms1024m -XX:+HeapDumpOnOutOfMemoryError
sonar.ce.javaOpts=-Xmx1024m -Xms1024m -XX:+HeapDumpOnOutOfMemoryError
sonar.search.javaOpts=-Xmx6g -Xms6g -XX:+HeapDumpOnOutOfMemoryError
# должны быть открыты порты (если выполняется на другой машине)
sonar.web.port=9000 
sonar.search.port=9001

sonar.projectKey=First1CSonar
sonar.projectName=First1CSonar
sonar.projectVersion=1.0

# Исходный код
sonar.sources=./src
sonar.tests=./tests

# Адрес SonarQube
sonar.host.url=http://localhost:9000

# Токен
sonar.token=sqp_c01c8f67992e84391df1f4baf1699afda5b24ff8

# Кодировка
sonar.sourceEncoding=UTF-8

# Какие файлы анализировать
sonar.inclusions=**/*.bsl,**/*.os

# Не учитывать .gitignore
sonar.scm.exclusions.disabled=true



